DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PHONES;

CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(15) NOT NULL,
  created DATE NOT NULL,
  modified DATE NOT NULL,
  last_login DATE NOT NULL,
  is_active BOOLEAN,
  token VARCHAR(100) NOT NULL
);

CREATE TABLE PHONES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  number INT NOT NULL,
  city_code INT NOT NULL,
  country_code INT NOT NULL,
  id_user INT NOT NULL
);

ALTER TABLE USERS ADD CONSTRAINT UK_EMAIL UNIQUE(email);
ALTER TABLE PHONES ADD CONSTRAINT FK_USERS FOREIGN KEY (id_user) REFERENCES USERS(id);
